application: yourswayhome
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images
- url: /javascript
  static_dir: static/javascript
- url: /css
  static_dir: static/css
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.ya?ml)|
 (index\.ya?ml)|
 (.*\.pxm)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$

